version: '3.9'

services:
  tickera-front:
    build: ./client
    container_name: tickera-front
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    networks:
      - tickera-network
  
  tickera-back:
    build: ./server
    container_name: tickera-back
    ports:
      - "3011:3011"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules 
    networks:
      - tickera-network

networks:
  tickera-network:
    driver: bridge 
   
